# Uncomment this line to define a global platform for your project
# platform :iOS, '8.0'
# Uncomment this line if you're using Swiftj
use_framworks!

target 'AerialScoutSwift' do
  pod 'Reachability', '~> 3.2'
end

target 'AerialScoutSwiftTest' do

end

target 'AerialScoutSwiftUITests' do

end